### PR TITLE
Copies + Rules / Flavor Text for Core Resources

### PR DESCRIPTION
**Pull request by superpowered**
Adds Copy counts to the 1.5 Core resources. 
Adds Rules Text / Flavor Text in addition to Description.
Add Rules Tables for qualifying vermin. Also added tables to Description.
Classes added to most Description tags. Classes added: "roll-table", "special-rule", "flavor-text", "story-event", "severe-injury", "waist"

### CODE REVIEW

**Comment by superpowered** [comment]
Force pushed back because I didn't realize pushing to master would continue adding to this PR.

Expansion stuff is now in it's own branch until it's closer to completion

**Comment by toconnell** [comment]
@superpowered Yeah, sorry about that: I should have warned you that I've been a one-man-army on the API since I broke off with the other original developer of KDM-Manager so I have just been raw-dogging everything right onto master haha.

**Comment by superpowered** [comment]
Yeah you're all good to merge this in. I've started on some of the expansions, but won't get to the rest of it until next week, likely.

**Comment by toconnell** [comment]
@superpowered Cool: I'll probably push another quick update to master later today or tomorrow, depending. Thanks again!

**Pull request merged**
