### PR TITLE
Severe injuries to be capitalized like the others

### PR DESCRIPTION
**Pull request by CalebKester**
Just trying to be consistent with the names and capitalization.

### CODE REVIEW

**Comment by toconnell** [comment]
@CalebKester Let's wait for 1.5 books before we make a ruling here, because in the 1.3 book, the capitalization is sentence-case (except in the case of the "Achilles Tendon", where the book has a typo and treats the phrase as a proper noun instead of using the standard usage, i.e. where Achilles is a noun):

severe_injuries

**Comment by CalebKester** [comment]
Sounds good. Another example of poor design in the manual :)

I'll just use css to standardize titles then. Thanks!

**Comment by toconnell** [comment]
@CalebKester I mean...that's kind of my point: there's an inconsistency, but we don't really know (until 1.5 boxes show up) whether the error is that some are in title case OR that some are _not_ in title case.

Right? I mean, not to get into some kind of literary theory debate about authorial intention, there is not really a clear grammatical rule to apply here: if these things were titles, you could say that they should all be title case, if they were all sentences, you could say that they should be sentence case, etc.

Since they're...neither sentences nor titles and since we don't really know what the intended capitalization scheme was, I think the pragmatic thing to do is to err on the side of "strict" construction, i.e. and represent them as they are represented in the rule books.

But yeah, like I said, I've got a strong feeling like the 1.5 book will give us a ruling, one way or the other.

**Comment by CalebKester** [comment]
1.5 book didn't change this. I'll just close this as your reasoning is fair :)

**Pull request closed without merging**
